version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages

      - run:
          name: Build
          command: |
            yarn install
            yarn build

      - run:
          name: Test
          command: yarn test --maxWorkers=2 --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/project
          paths: dest*

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish Packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
            npm publish dest && npm publish dest-es

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
