name: nodejs

on:
  push:
    branches:
      - master

jobs:

  test-node:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 8.x, 10.x, 12.x, 13.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node-hid requirements
        run: sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev libudev-dev

      - name: Install dependencies (and link per package)
         run: |
           cd web3x-codegen/
           yarn install
           yarn build

